// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5L8MLfj2Vi8-NnLPNl-P9FGVMTWZarhg',
    appId: '1:605554417931:android:567e8fe74341e34ac2020e',
    messagingSenderId: '605554417931',
    projectId: 'yevmiyedefterim-f8a83',
    storageBucket: 'yevmiyedefterim-f8a83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2pOSpIXaanDxY9Jp6AH-5yUgO2iMPVo',
    appId: '1:605554417931:ios:60b3e6c6b360b5ecc2020e',
    messagingSenderId: '605554417931',
    projectId: 'yevmiyedefterim-f8a83',
    storageBucket: 'yevmiyedefterim-f8a83.firebasestorage.app',
    iosBundleId: 'com.husrevkorpe.yevmiyedefterim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2pOSpIXaanDxY9Jp6AH-5yUgO2iMPVo',
    appId: '1:605554417931:ios:60b3e6c6b360b5ecc2020e',
    messagingSenderId: '605554417931',
    projectId: 'yevmiyedefterim-f8a83',
    storageBucket: 'yevmiyedefterim-f8a83.firebasestorage.app',
    iosBundleId: 'com.husrevkorpe.yevmiyedefterim',
  );
}
